### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined function EDD_FES() 

### ISSUE THREAD

**Issue by dgoldak** [easydigitaldownloads/edd-slack#107]
With Slack & Reviews both enabled, the following error occurs when viewing Slack settings page:

[13-Mar-2020 22:25:36 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function EDD_FES() in /app/public/wp-content/plugins/edd-slack/core/integrations/edd-reviews/class-edd-slack-reviews.php:423
Stack trace:
#0 /app/public/wp-includes/class-wp-hook.php(286): EDD_Slack_Reviews->custom_replacement_hints(Array, Array, Array)
#1 /app/public/wp-includes/plugin.php(208): WP_Hook->apply_filters(Array, Array)
#2 /app/public/wp-content/plugins/edd-slack/core/admin/class-edd-slack-admin.php(440): apply_filters('edd_slack_text_...', Array, Array, Array)
#3 /app/public/wp-content/plugins/edd-slack/core/admin/class-edd-slack-admin.php(376): EDD_Slack_Admin->get_replacement_hints()
#4 /app/public/wp-includes/class-wp-hook.php(286): EDD_Slack_Admin->replacement_hints_field(Array)
#5 /app/public/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#6 /app/public/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#7 /app/public/wp-content/plugins/easy-digital-downloads/includes/admin/settings/register-settings.php(2531): do_action('edd_repl in /app/public/wp-content/plugins/edd-slack/core/integrations/edd-reviews/class-edd-slack-reviews.php on line 423

The Slack Settings page fails to load:
<img width="1814" alt="Screen Shot 2020-03-13 at 5 32 57 PM" src="https://user-images.githubusercontent.com/30910807/76663939-bf548d80-6550-11ea-9bd1-d5b9b8c7cd87.png">

https://secure.helpscout.net/conversation/1106539656/147678?folderId=1847242

**Comment by nutsandbolts** [comment]
Another user experiencing this issue: https://secure.helpscout.net/conversation/1158169369/153363?folderId=2657915

**Comment by shaynesanderson** [comment]
And another: https://secure.helpscout.net/conversation/1205058854/158290?folderId=3668571
